service: example-s3-signedurl

provider:
  name: aws
  region: us-east-1
  runtime: java8
  iam:
    role: LambdaRole
  stage: ${opt:stage}
  apiGateway:
    shouldStartNameWithService: true

package:
  individually: true

functions:
  s3:
    handler: com.pigumer.example.s3.App
    events:
      - http:
          path: s3/signedurl/{path+}
          method: get
    package:
      artifact: "modules/s3/signedurl/target/s3-example-s3-0.1.0-SNAPSHOT.jar"
    environment:
      BUCKET_NAME:
        Ref: S3
  cf:
    handler: com.pigumer.example.cloudfront.App
    events:
      - http:
          path: cf/signedurl/{path+}
          method: get
    package:
      artifact: "modules/cloudfront/signedurl/target/s3-example-cloudfront-0.1.0-SNAPSHOT.jar"
    environment:
      KEY_BUCKET_NAME: ${env:KEY_BUCKET_NAME}
      KEY_PAIR_ID: ${env:KEY_PAIR_ID}
      KEY_FILE: ${env:KEY_FILE}
      DOMAIN_NAME:
        Fn::GetAtt:
          - CloudFront
          - DomainName

resources:
  Resources:
    S3:
      Type: AWS::S3::Bucket
      Properties:
        VersioningConfiguration:
          Status: Enabled
    OriginAccessIdentity:
      Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
      Properties:
        CloudFrontOriginAccessIdentityConfig:
          Comment: test
    BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: S3
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                AWS:
                  Fn::Join:
                    - ' '
                    - - 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity'
                      - Ref: OriginAccessIdentity
              Action:
                - 's3:*'
              Resource:
                Fn::Join:
                  - ''
                  - - 'arn:aws:s3:::'
                    - Ref: S3
                    - '/*'
    CachePolicy:
      Type: AWS::CloudFront::CachePolicy
      Properties:
        CachePolicyConfig:
          DefaultTTL: 86400
          MaxTTL: 31536000
          MinTTL: 0
          Name: s3-example-cache-policy
          ParametersInCacheKeyAndForwardedToOrigin:
            CookiesConfig:
              CookieBehavior: none
            EnableAcceptEncodingGzip: true
            HeadersConfig:
              HeaderBehavior: none
            QueryStringsConfig:
              QueryStringBehavior: whitelist
              QueryStrings:
                - versionId
    CloudFront:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Origins:
            - DomainName:
                Fn::Join:
                  - '.'
                  - - Ref: S3
                    - 's3'
#                   - Ref: AWS::Region
                    - Ref: AWS::URLSuffix
              Id: testOrigin
              S3OriginConfig:
                OriginAccessIdentity:
                  Fn::Join:
                    - '/'
                    - - origin-access-identity
                      - cloudfront
                      - Ref: OriginAccessIdentity
          Enabled: true
          DefaultCacheBehavior:
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - PATCH
              - POST
              - DELETE
            CachePolicyId:
              Ref: CachePolicy
            TargetOriginId: testOrigin
            TrustedKeyGroups:
              - ${env:KEY_GROUP}
            ViewerProtocolPolicy: https-only
    LambdaRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /
        RoleName: example-s3-signedurl-${opt:stage}
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
          - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
        Policies:
          - PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - s3:*
                    - cloudfront:*
                  Resource: '*'
            PolicyName: policy-for-lambda-${opt:stage}
